[package]
name = "day08"
version = "0.1.0"
authors = ["Daniel Patrick <danielpatrick@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
